"""add body_html

Revision ID: 0b795f7239ca
Revises: 2044dab977fb
Create Date: 2018-08-18 21:07:20.755606

"""

# revision identifiers, used by Alembic.
revision = '0b795f7239ca'
down_revision = '2044dab977fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
