"""add post

Revision ID: 2044dab977fb
Revises: 0df9f60e947b
Create Date: 2018-08-16 21:47:59.006908

"""

# revision identifiers, used by Alembic.
revision = '2044dab977fb'
down_revision = '0df9f60e947b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
