"""add md5

Revision ID: b6c26428d358
Revises: e5160af6be84
Create Date: 2018-08-14 22:01:16.804952

"""

# revision identifiers, used by Alembic.
revision = 'b6c26428d358'
down_revision = 'e5160af6be84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
