"""change user

Revision ID: e5160af6be84
Revises: 29422b4217eb
Create Date: 2018-08-13 22:25:38.045590

"""

# revision identifiers, used by Alembic.
revision = 'e5160af6be84'
down_revision = '29422b4217eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
